services:
  - type: web
    name: newsfeedback
    env: python
    buildCommand: pip install -r requirements.txt && python manage.py migrate
    startCommand: gunicorn newsfeedback.wsgi:application --bind 0.0.0.0:$PORT
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: newsfeedback.settings
      - key: PYTHON_VERSION
        value: 3.11.0

